# Generated by Django 5.1.2 on 2026-01-28 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_utils", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="考勤日期")),
                (
                    "sign_in_time",
                    models.DateTimeField(blank=True, help_text="签到时间", null=True),
                ),
                (
                    "sign_out_time",
                    models.DateTimeField(blank=True, help_text="签退时间", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        default="normal",
                        help_text="状态：normal/late/leave",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
